---
title: "PICRUSt"
author: "Aidan Chance"
date: "2026-03-18"
output: html_document
---

# Loading packages

```{r}

library(tidyverse)
library(ggpicrust2)
library(phyloseq)
```

# Loading and filtering metadata and MetaCyc data

```{r}

metadata = read.csv('anemia_metadata.csv', row.names = 1) %>% 
  rownames_to_column('sample_name') %>%
  filter(supplement %in% c("MNP","FeSO4","None"), 
         age_months == 12,
         anemia == "anemic") %>% 
  select(sample_name, supplement) %>% 
  filter(!if_any(everything(), ~ . == "Missing: Not collected"))

metadata_mnp_none = metadata %>% 
  filter(supplement %in% c('MNP', 'None'))

metadata_mnp_feso4 = metadata %>% 
  filter(supplement %in% c('MNP', 'FeSO4'))

metadata_feso4_none = metadata %>% 
  filter(supplement %in% c('FeSO4', 'None'))
  
  
metacyc_data_mnp_none = read.delim('path_abun_unstrat.tsv', 
                          row.names = 1,
                          check.names = FALSE) %>% 
  select(all_of(metadata_mnp_none$sample_name))  

metacyc_data_mnp_feso4 = read.delim('path_abun_unstrat.tsv', 
                          row.names = 1,
                          check.names = FALSE) %>% 
  select(all_of(metadata_mnp_feso4$sample_name))

metacyc_data_feso4_none = read.delim('path_abun_unstrat.tsv', 
                          row.names = 1,
                          check.names = FALSE) %>% 
  select(all_of(metadata_feso4_none$sample_name))
```

# Maaslin2

```{r}

library(Maaslin2)

daa_results_df_mnp_none = pathway_daa(abundance = metacyc_data_mnp_none,
                             metadata = metadata_mnp_none,
                             group = 'supplement',
                             daa_method = 'Maaslin2',
                             select = NULL, reference = NULL)

daa_results_df_mnp_feso4 = pathway_daa(abundance = metacyc_data_mnp_feso4,
                             metadata = metadata_mnp_feso4,
                             group = 'supplement',
                             daa_method = 'Maaslin2',
                             select = NULL, reference = NULL)

daa_results_df_feso4_none = pathway_daa(abundance = metacyc_data_feso4_none,
                             metadata = metadata_feso4_none,
                             group = 'supplement',
                             daa_method = 'Maaslin2',
                             select = NULL, reference = NULL)
```

# Annotations

```{r}

daa_annotated_results_df_mnp_none = pathway_annotation(pathway = "MetaCyc",
                                              daa_results_df = daa_results_df_mnp_none,
                                              ko_to_kegg = FALSE)

daa_annotated_results_df_mnp_feso4 = pathway_annotation(pathway = "MetaCyc",
                                              daa_results_df = daa_results_df_mnp_feso4,
                                              ko_to_kegg = FALSE)

daa_annotated_results_df_feso4_none = pathway_annotation(pathway = "MetaCyc",
                                              daa_results_df = daa_results_df_feso4_none,
                                              ko_to_kegg = FALSE)
```

# Visualization

```{r}

# source('ggpicrust2_errorbar_function_fixed.R')

daa_annotated_results_df_mnp_none %>% filter(p_adjust < 0.05) %>% nrow()

daa_annotated_results_df_mnp_feso4 %>% filter(p_adjust < 0.05) %>% nrow()

daa_annotated_results_df_feso4_none %>% filter(p_adjust < 0.05) %>% nrow()


# MNP vs None
volcano_mnp_none <- daa_annotated_results_df_mnp_none %>%
  ggplot(aes(x = log2_fold_change, y= -log10(p_adjust)))+
  geom_point(size = 3, alpha = 0.3, color = "black")+
  theme_minimal()+
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", alpha = 0.5)+
  labs(title = "Functional Abundance of Predicted Pathways - MNP vs None",
       x = "Log2 Fold Change",
       y = "-log10(p-adjusted)")+
  theme(legend.position = "bottom")+
  scale_y_continuous()+
  scale_x_continuous()+
  theme(plot.title = element_text(size = 13, face = "bold"),
        axis.title = element_text(size=12),
        legend.position = "bottom")


# FeSO4 vs None
volcano_feso4_none <- daa_annotated_results_df_feso4_none %>%
  ggplot(aes(x = log2_fold_change, y= -log10(p_adjust)))+
  geom_point(size = 3, alpha = 0.3, color = "black")+
  theme_minimal()+
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", alpha = 0.5)+
  labs(title = "Functional Abundance of Predicted Pathways - FeSO4 vs None",
       x = "Log2 Fold Change",
       y = "-log10(p-adjusted)")+
  theme(legend.position = "bottom")+
  scale_y_continuous()+
  scale_x_continuous()+
  theme(plot.title = element_text(size = 13, face = "bold"),
        axis.title = element_text(size=12),
        legend.position = "bottom")


# MNP vs FeSO4
volcano_mnp_feso4 <- daa_annotated_results_df_mnp_feso4 %>%
  ggplot(aes(x = log2_fold_change, y= -log10(p_adjust)))+
  geom_point(size = 3, alpha = 0.3, color = "black")+
  theme_minimal()+
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", alpha = 0.5)+
  labs(title = "Functional Abundance of Predicted Pathways - MNP vs FeSO4",
       x = "Log2 Fold Change",
       y = "-log10(p-adjusted)")+
  theme(legend.position = "bottom")+
  scale_y_continuous()+
  scale_x_continuous()+
  theme(plot.title = element_text(size = 13, face = "bold"),
        axis.title = element_text(size=12),
        legend.position = "bottom")

ggsave("volcano-mnp-none.png",
       plot = volcano_mnp_none, width = 18, height = 10)

ggsave("volcano-feso4-none.png",
       plot = volcano_feso4_none, width = 18, height = 10)

ggsave("volcano-plot-mnp-feso4.png",
       plot = volcano_mnp_feso4, width = 18, height = 10)
```
